.\" Manpage for the-powder-toy
.TH man 6 "05 May 2012"
.SH NAME
.BR the-powder-toy
\- a physics sandbox that simulates air pressure and velocity as well as heat! 
.SH SYNOPSIS
the-powder-toy [scale:1|scale:2] [kiosk] [proxy:<server>:<port>] [open <file>] [ddir <directory>] [nohud] [sound] [scripts]
.SH DESCRIPTION
The Powder Toy is a desktop version of the classic 'falling sand' physics sandbox game. It simulates air pressure and velocity as well as heat! 
.SH OPTIONS
.BR "scale:1"
\- use the normal window resolution
.P
.BR "scale:2"
\- use a doubled window resolution
.P
.BR "kiosk"
\- use a fullscreen window
.P
.BR "proxy:<server>:<port>"
\- use a proxy with at <server> with port <port>
.P
.BR "open <file>"
\- open the file as a stamp or game save
.P
.BR "ddir <directory>"
\- use <directory> for saving stamps and preferences. The default is ./
.P
.BR "nohud"
\- disable the in-game HUD
.P
.BR "sound"
\- enable sounds to be played from the in-game console
.P
.BR "scripts"
\- enable scripts to be run from the old in-game console
.SH AUTHOR
The Powder Toy was originally written by Stanislaw K Skowronek. See the README file for the complete list of authors.

